---
- name: Generate Private Key
  shell: wg genkey
  register: wireguard_genkey
  changed_when: false

- set_fact:
        private_key: "{{ wireguard_genkey.stdout }}"

- name: Generate Public Key
  shell: "echo {{ private_key }} | wg pubkey"
  register: wireguard_pubkey
  changed_when: false

- set_fact:
        public_key: "{{ wireguard_pubkey.stdout }}"

- set_fact: 
        private_ip: "10.0.0.{{ groups['wireguard'].index(inventory_hostname) + 2 }}"

- name: Create wireguard directory
  file:
          path: /etc/wireguard
          state: directory

- name: Configure wireguard
  template:
          src: wg.conf.j2
          dest: /etc/wireguard/wg0.conf
          owner: root
          group: root
          mode: 600
  notify: wg0_restart


